---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Writing your lab"
      solveButton: true
    - name: module-02
      label: "Antora"
      solveButton: true
    - name: module-03
      label: "Tabs"

tabs:
  - name: "VSCode"
    url: https://vscode-${guid}.${domain}/?folder=/home/rhel/
    external: false
  - name: ">_ terminal"
    url: /wetty_vscode/ssh/root
  - name: "GitHub"
    url: https://github.com/rhpds/lab_zero_touch_template/tree/main
    external: true
