---
containers: []
virtualmachines:
  - name: "vscode"
    image: "rhel-9.6"
    memory: "8G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    services:
      - name: vscode
        ports:
          - port: 9090
            protocol: TCP
            targetPort: 9090
            name: vscode
    routes:
      - name: vscode
        host: vscode
        service: vscode
        targetPort: 9090
        tls: true
        tls_termination: Edge